import { Random } from '../utils/Random';
import { ClusterData, SystemData, PlanetData, StarType } from './types';
import { ResourceType } from '../economy/types';

export class LatticeGenerator {
  private universeSeed: string;

  constructor(universeSeed: string) {
    this.universeSeed = universeSeed;
  }

  /**
   * Generates metadata for a specific cluster.
   */
  generateCluster(x: number, y: number): ClusterData {
    const clusterSeed = `${this.universeSeed}-${x}-${y}`;
    const random = new Random(clusterSeed);

    const systems: SystemData[] = [];
    for (let i = 0; i < 10; i++) {
      systems.push(this.generateSystem(clusterSeed, i, random));
    }

    // Identify 1-2 center systems (first ones for simplicity in this MVP)
    const centers = [systems[0].id];
    if (random.chance(0.5)) {
      centers.push(systems[1].id);
    }

    return {
      id: `cluster-${x}-${y}`,
      coords: { x, y },
      systems,
      centers,
      routes: [] // Routes are generated by RouteGenerator
    };
  }

  private generateSystem(clusterSeed: string, index: number, clusterRandom: Random): SystemData {
    const systemSeed = `${clusterSeed}-sys-${index}`;
    const random = new Random(systemSeed);

    const starTypes: StarType[] = ['YellowDwarf', 'RedGiant', 'BlueGiant', 'NeutronStar'];
    const starType = random.pick(starTypes);

    const planets: PlanetData[] = [];
    const planetCount = random.nextInt(1, 11);
    for (let i = 0; i < planetCount; i++) {
      planets.push(this.generatePlanet(systemSeed, i));
    }

    return {
      id: `${clusterSeed}-s${index}`,
      name: `System ${index}`,
      starType,
      position: {
        x: clusterRandom.nextFloat(-500, 500),
        y: clusterRandom.nextFloat(-500, 500),
        z: clusterRandom.nextFloat(-100, 100)
      },
      planets
    };
  }

  private generatePlanet(systemSeed: string, index: number): PlanetData {
    const planetSeed = `${systemSeed}-p-${index}`;
    const random = new Random(planetSeed);

    const resourceDensitySeeds: Partial<Record<ResourceType, string>> = {};
    Object.values(ResourceType).forEach(type => {
      resourceDensitySeeds[type] = `${planetSeed}-res-${type}`;
    });

    return {
      id: `${systemSeed}-p${index}`,
      name: `Planet ${index}`,
      radius: random.nextFloat(10, 50),
      orbitDistance: (index + 1) * 100 + random.nextFloat(-20, 20),
      color: Math.floor(random.next() * 0xffffff),
      heightmapSeed: `${planetSeed}-heightmap`,
      resourceDensitySeeds,
      spaceGrid: {
        radius: 100, // 2x max radius approx
        resolution: 32
      }
    };
  }
}
